export const UPDATE_LIST = "UPDATE_LIST";
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const SHOW_CONFIRM_MODAL = "SHOW_CONFIRM_MODAL";
export const CLOSE_CONFIRM_MODAL = "CLOSE_CONFIRM_MODAL";
export const UPDATE_BUDGET_VALUE = "UPDATE_BUDGET_VALUE";